# fly.toml app configuration file generated for synthwave-stack on 2023-08-02T11:23:21+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "synthwave-stack"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.status]
    port = 3000
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/api/health"
    protocol = "http"
    tls_skip_verify = false
